### PR TITLE
configure: Fix checks for libjpeg and libexif

### PR DESCRIPTION
**Pull request by kraj**
Use the functions from the respective library instead of using main
function which is not part of library

Upstream-Status: Pending
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by mattes** [comment]
@francois-random Does this look good to you?

**Comment by kraj** [comment]
> there misses a dependency to -lm in AC_CHECK_LIB in case libexif is a static lib (at least for the latest version of libexif, perhaps it wasnt needed before).
> 
> it should be `AC_CHECK_LIB([jpeg], [jpeg_simple_progression], [], [echo "libjpeg library not found. Please install it before proceeding"; exit -1])` ` AC_CHECK_LIB([exif], [exif_data_new_from_file], [], [echo "libexif library not found. Please install it before proceeding"; exit -1], [-lm])`

done

**Comment by kraj** [comment]
> great! to build successfully the command line tool and the shared libraries, there needs 2 more lines to reference -lm:
> 
> ```
> AC_CHECK_LIB([jpeg], [jpeg_simple_progression], [], [echo "libjpeg library not found. Please install it before proceeding"; exit -1])
> AC_CHECK_LIB([exif], [exif_data_new_from_file], [], [echo "libexif library not found. Please install it before proceeding"; exit -1], [-lm])
> AC_CHECK_LIB([m], [log], [], [echo "invalid libm. log not found"])
> 
> my_includes=""
> my_libs="-ljpeg -lexif -lm"
> ```
> 
> its because now there are references to log, log10 and pow in the latest version of libexif

I have gone a step further to get rid of `my_includes` and `my_libs` they will be automatically added when configure checks for these libs succeed so no need to have them. They were making the libs appear twice on linker cmdline

**Comment by francois-random** [comment]
@kraj this is perfect, thanks
@mattes I confirm it works for me

**Comment by mattes** [comment]
Amazing team work! Thank you @francois-random and @kraj

**Pull request merged**
